# Generated by Django 5.2.15 on 2026-07-04 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='confirmed', max_length=12, verbose_name='estado')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='código')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reserva',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BookingSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveSmallIntegerField(verbose_name='asiento')),
                ('passenger_name', models.CharField(max_length=150, verbose_name='pasajero')),
                ('passenger_document', models.CharField(max_length=20, verbose_name='documento')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.booking')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_seats', to='catalog.trip')),
            ],
            options={
                'verbose_name': 'asiento reservado',
                'constraints': [models.UniqueConstraint(fields=('trip', 'seat_number'), name='unique_trip_seat')],
            },
        ),
    ]
