# Generated by Django 5.2.15 on 2026-07-04 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=16, unique=True, verbose_name='código de rastreo')),
                ('recipient_name', models.CharField(max_length=150, verbose_name='destinatario')),
                ('recipient_document', models.CharField(max_length=20, verbose_name='documento')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='peso (kg)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio')),
                ('status', models.CharField(choices=[('registered', 'Registrado'), ('in_transit', 'En tránsito'), ('at_destination', 'En destino'), ('delivered', 'Entregado')], default='registered', max_length=16, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_to', to='catalog.city', verbose_name='destino')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments_from', to='catalog.city', verbose_name='origen')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'encomienda',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registrado'), ('in_transit', 'En tránsito'), ('at_destination', 'En destino'), ('delivered', 'Entregado')], max_length=16, verbose_name='estado')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='ubicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='parcels.shipment')),
            ],
            options={
                'verbose_name': 'evento de rastreo',
                'ordering': ('created_at',),
            },
        ),
    ]
