# Generated by Django 5.2.15 on 2026-07-04 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='placa')),
                ('model', models.CharField(max_length=100, verbose_name='modelo')),
                ('seat_rows', models.PositiveSmallIntegerField(verbose_name='filas')),
                ('seat_cols', models.PositiveSmallIntegerField(verbose_name='columnas')),
                ('aisle_after_col', models.PositiveSmallIntegerField(default=2, verbose_name='pasillo después de columna')),
            ],
            options={
                'verbose_name': 'bus',
                'verbose_name_plural': 'buses',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('region', models.CharField(max_length=100, verbose_name='región')),
            ],
            options={
                'verbose_name': 'ciudad',
                'verbose_name_plural': 'ciudades',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.PositiveIntegerField(verbose_name='distancia (km)')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='duración (min)')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio base')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_to', to='catalog.city', verbose_name='destino')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_from', to='catalog.city', verbose_name='origen')),
            ],
            options={
                'verbose_name': 'ruta',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_at', models.DateTimeField(verbose_name='salida')),
                ('arrival_at', models.DateTimeField(verbose_name='llegada')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio')),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('cancelled', 'Cancelado'), ('completed', 'Completado')], default='scheduled', max_length=12, verbose_name='estado')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='catalog.bus', verbose_name='bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='catalog.route', verbose_name='ruta')),
            ],
            options={
                'verbose_name': 'viaje',
                'ordering': ('departure_at',),
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['origin', 'destination'], name='catalog_rou_origin__b3da0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('origin', 'destination'), name='unique_route'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('origin', models.F('destination')), _negated=True), name='route_origin_not_destination'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['departure_at'], name='catalog_tri_departu_a8d501_idx'),
        ),
    ]
