# Generated by Django 5.2.15 on 2026-07-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bus',
            constraint=models.CheckConstraint(condition=models.Q(('aisle_after_col__lt', models.F('seat_cols'))), name='bus_aisle_within_columns'),
        ),
    ]
